# Generated by Django 2.2.10 on 2020-08-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.User_category', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='join_as',
            field=models.ManyToManyField(to='category.user_type', verbose_name='join_as'),
        ),
    ]
