# Generated by Django 2.2.10 on 2020-08-19 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='destination_detail',
            new_name='dest_detail',
        ),
        migrations.RenameModel(
            old_name='destination_photo',
            new_name='dest_photo',
        ),
        migrations.RenameModel(
            old_name='destination_video',
            new_name='dest_video',
        ),
        migrations.RenameField(
            model_name='dest_photo',
            old_name='destination_detail',
            new_name='dest_detail',
        ),
        migrations.RenameField(
            model_name='dest_video',
            old_name='destination_detail',
            new_name='dest_detail',
        ),
    ]
