# Generated by Django 2.2.10 on 2020-08-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=300)),
                ('zipcode', models.IntegerField()),
                ('about_hotel', models.TextField(max_length=300)),
                ('room_type', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('linkdin', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('google_user', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
    ]
