# Generated by Django 2.2.10 on 2020-08-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200826_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('zipcode', models.IntegerField()),
                ('about_hotel', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('linkdin', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('google_user', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='post_hotel',
        ),
    ]
